### ISSUE TITLE
PyPi Package

### ISSUE THREAD

**Issue by logan-markewich** [cyr19/MENLI#1]
Hi, and thanks for the interesting work here!

Have you considered publishing this as a package on pypi? Would love to be able to add this as a dependency to projects.

**Comment by cyr19** [comment]
Hi!

Thanks. Yes, I do intend to release this as a PyPI package. As I’m currently occupied with other things, I will probably start in a few weeks. Will let you know once I’m done.

Best,

**Comment by cyr19** [comment]
hi @logan-markewich ,

i've published a demo version of menli metrics on pypi. Will update the instructions later. You can check https://pypi.org/project/menli/ if you're still interested. Thanks!

best,

**Comment by logan-markewich** [comment]
Amazing, I will try it out! Thanks a ton!
